# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# https://circleci.com/docs/2.0/orb-intro/
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0
  # https://circleci.com/developer/orbs/orb/circleci/heroku
  heroku: circleci/heroku@2.0.0
  # https://circleci.com/developer/orbs/orb/circleci/docker
  docker: circleci/docker@2.1.4

# https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python manage.py test
      - run:
          name: Run flake8
          command: flake8
  deploy-to-heroku:
    docker:
      - image: cimg/base:stable
    steps:
      - heroku/install
      - setup_remote_docker
      - run:
          name: Pull from Dockerhub
          command: |
            docker login --username=$DOCKER_LOGIN --password=$DOCKER_PASSWORD
            docker pull $DOCKER_LOGIN/$HEROKU_APP_NAME:latest
      - run:
          name: Push to Heroku
          command: |
            heroku container:login
            docker tag $DOCKER_LOGIN/$HEROKU_APP_NAME:latest registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            # heroku container:push -a $HEROKU_APP_NAME web
            heroku container:release -a $HEROKU_APP_NAME  web

# https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy:
    jobs:
      - test-and-lint
      - docker/publish:
          requires:
            - test-and-lint
          filters:
            branches:
              only: master
          image: $DOCKER_LOGIN/$HEROKU_APP_NAME
          tag: $CIRCLE_SHA1,latest
      - deploy-to-heroku:
          requires:
            - test-and-lint
            - docker/publish
          filters:
            branches:
              only: master
